### ISSUE TITLE
mall-admin 无法启动

### ISSUE THREAD

**Issue by imaoxian** [macrozheng/mall#212]
os: windows 10
java version "1.8.0_141"
Apache Maven 3.6.2 
请问如何解决啊
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2019-10-08 15:52:44.299  INFO 12456 --- [           main] com.macro.mall.MallAdminApplication      : Starting MallAdminApplication on LAPTOP-HUUP5LI2 with PID 12456 (D:\Git\mall\mall-admin\target\classes started by imaoxian in D:\Git\mall)
2019-10-08 15:52:44.303 DEBUG 12456 --- [           main] com.macro.mall.MallAdminApplication      : Running with Spring Boot v2.1.3.RELEASE, Spring v5.1.5.RELEASE
2019-10-08 15:52:44.304  INFO 12456 --- [           main] com.macro.mall.MallAdminApplication      : The following profiles are active: dev
2019-10-08 15:52:46.656  INFO 12456 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$35807c81] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-08 15:52:46.838  INFO 12456 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-08 15:52:46.845  INFO 12456 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@5d5b9ecb' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-08 15:52:46.860  INFO 12456 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$5a551f33] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-08 15:52:46.879  INFO 12456 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-08 15:52:46.913  INFO 12456 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$9cd2b447] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-08 15:52:47.782  INFO 12456 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2019-10-08 15:52:47.812  INFO 12456 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-10-08 15:52:47.813  INFO 12456 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2019-10-08 15:52:47.825  INFO 12456 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in 
production environments was not found on the java.library.path: [C:\Program Files\Java\jdk1.8.0_141\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\ProgramData\Oracle\Java\javapath;C:\Python\Python37\Scripts\;C:\Python\Python37\;C:\Program Files (x86)\NetSarang\Xftp 6\;C:\Program Files (x86)\NetSarang\Xshell 6\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\toos_dev\apache-maven-3.6.2\bin;C:\Users\imaoxian\AppData\Local\Microsoft\WindowsApps;;.]
2019-10-08 15:52:47.920  INFO 12456 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-10-08 15:52:47.921  INFO 12456 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3563 ms
2019-10-08 15:52:48.276  INFO 12456 --- [           main] c.a.d.s.b.a.DruidDataSourceAutoConfigure : Init DruidDataSource
2019-10-08 15:53:40.665  INFO 12456 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2019-10-08 15:53:42.905 DEBUG 12456 --- [           main] c.m.m.c.JwtAuthenticationTokenFilter     : Filter 'jwtAuthenticationTokenFilter' configured for use
2019-10-08 15:53:42.990  WARN 12456 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'omsOrderController': Unsatisfied dependency expressed through field 'orderService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'omsOrderServiceImpl' defined in file [D:\Git\mall\mall-admin\target\classes\com\macro\mall\service\impl\OmsOrderServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.macro.mall.service.impl.OmsOrderServiceImpl]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems:
        The method getOrderId() is undefined for the type OmsOrderDeliveryParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getReceiverName() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPhone() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPostCode() is undefined for the type OmsReceiverInfoParam
        The method getReceiverDetailAddress() is undefined for the type OmsReceiverInfoParam
        The method getReceiverProvince() is undefined for the type OmsReceiverInfoParam
        The method getReceiverCity() is undefined for the type OmsReceiverInfoParam
        The method getReceiverRegion() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getStatus() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getFreightAmount() is undefined for the type OmsMoneyInfoParam
        The method getDiscountAmount() is undefined for the type OmsMoneyInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getStatus() is undefined for the type OmsMoneyInfoParam

2019-10-08 15:53:43.023  INFO 12456 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
2019-10-08 15:53:43.029  INFO 12456 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-10-08 15:53:43.059  INFO 12456 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-10-08 15:53:43.066 ERROR 12456 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'omsOrderController': Unsatisfied dependency expressed through field 'orderService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'omsOrderServiceImpl' defined in file [D:\Git\mall\mall-admin\target\classes\com\macro\mall\service\impl\OmsOrderServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.macro.mall.service.impl.OmsOrderServiceImpl]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems:
        The method getOrderId() is undefined for the type OmsOrderDeliveryParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getReceiverName() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPhone() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPostCode() is undefined for the type OmsReceiverInfoParam
        The method getReceiverDetailAddress() is undefined for the type OmsReceiverInfoParam
        The method getReceiverProvince() is undefined for the type OmsReceiverInfoParam
        The method getReceiverCity() is undefined for the type OmsReceiverInfoParam
        The method getReceiverRegion() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getStatus() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getFreightAmount() is undefined for the type OmsMoneyInfoParam
        The method getDiscountAmount() is undefined for the type OmsMoneyInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getStatus() is undefined for the type OmsMoneyInfoParam

        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.macro.mall.MallAdminApplication.main(MallAdminApplication.java:13)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'omsOrderServiceImpl' defined in file [D:\Git\mall\mall-admin\target\classes\com\macro\mall\service\impl\OmsOrderServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.macro.mall.service.impl.OmsOrderServiceImpl]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems:
        The method getOrderId() is undefined for the type OmsOrderDeliveryParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getReceiverName() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPhone() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPostCode() is undefined for the type OmsReceiverInfoParam
        The method getReceiverDetailAddress() is undefined for the type OmsReceiverInfoParam
        The method getReceiverProvince() is undefined for the type OmsReceiverInfoParam
        The method getReceiverCity() is undefined for the type OmsReceiverInfoParam
        The method getReceiverRegion() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getStatus() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getFreightAmount() is undefined for the type OmsMoneyInfoParam
        The method getDiscountAmount() is undefined for the type OmsMoneyInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getStatus() is undefined for the type OmsMoneyInfoParam

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1287)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
        ... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.macro.mall.service.impl.OmsOrderServiceImpl]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems:
        The method getOrderId() is undefined for the type OmsOrderDeliveryParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getReceiverName() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getReceiverName() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPhone() is undefined for the type OmsReceiverInfoParam
        The method getReceiverPostCode() is undefined for the type OmsReceiverInfoParam
        The method getReceiverDetailAddress() is undefined for the type OmsReceiverInfoParam
        The method getReceiverProvince() is undefined for the type OmsReceiverInfoParam
        The method getReceiverCity() is undefined for the type OmsReceiverInfoParam
        The method getReceiverRegion() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsReceiverInfoParam
        The method getStatus() is undefined for the type OmsReceiverInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getFreightAmount() is undefined for the type OmsMoneyInfoParam
        The method getDiscountAmount() is undefined for the type OmsMoneyInfoParam
        The method getOrderId() is undefined for the type OmsMoneyInfoParam
        The method getStatus() is undefined for the type OmsMoneyInfoParam

        at com.macro.mall.service.impl.OmsOrderServiceImpl.<init>(OmsOrderServiceImpl.java:49)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
        ... 32 common frames omitted
```

**Comment by DukeGJ** [comment]
你好像缺少lombok插件，导致类在build是没有自动生成get和set方法
