### ISSUE TITLE
redis 长时间不使用再使用会报 command timeout 错误的问题

### ISSUE THREAD

**Issue by hdtopku** [macrozheng/mall#447]
mall项目使用缓存过程中，redis连接超时会报错，返回500，造成获取数据失败，需要再次请求才能获得数据
```
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 300 millisecond(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:167)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
### 问题描述
> 在springboot项目里使用redis做队列的，使用过程中会遇到短时间不操作（五分钟左右），redis连接就断开了，再使用redis时会报连接超时，此次操作会失败，然后几秒内会重连，重新连上之后又可以正常往redis写东西了

### 解决方案

1 、亲测有效：Redis 服务端 通过 tcp-keepalive 发送 ack 达到超活检测效果 官方建议设置 60s 时间
redis客户端执行：`CONFIG SET tcp-keepalive 60`，重启redis客户端。
2、心跳检测，如下
```
@Scheduled(cron = "0/10 * * * * *")
public void timer() {
    redisTemplate.opsForValue().get("heartbeat");
}
```
### 以下亲测无效
3、亲测无效：~~[改为jedis依赖](https://my.oschina.net/u/3740959/blog/4560638)。（我采用该方案，注意Jedis对象线程不安全(Lettuce对象是线程安全的）~~
```
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-commons</artifactId>
    <version>${spring-data-commons.version}</version>
    <exclusions>
        <exclusion>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
        </exclusion>
        <exclusion>
            <artifactId>lettuce-core</artifactId>
            <groupId>io.lettuce</groupId>
        </exclusion>
    </exclusions>
</dependency>
<!-- 解决redis超时io.lettuce.core.RedisCommandTimeoutException -->
<dependency>
    <groupId>redis.clients</groupId>
    <artifactId>jedis</artifactId>
</dependency>
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-pool2</artifactId>
</dependency>
```
4、亲测无效：~~升级 lettuce-core 至 5.3.0+，
（具体看此 [Fix infinite command timeout #1260](https://github.com/lettuce-io/lettuce-core/issues/1269) ）~~

### 参考
> 1、[请教一个 redis 长时间不使用再使用会报 command timeout 错误的问题](https://v2ex.com/t/693771)、
2、[springboot2.0.3 redis一会不操作会自动断开连接 队列channel监听器失效](https://www.jianshu.com/p/36be264926b0)
3、[springboot系列文章之 集成redis 服务 (Lettuce & Jedis)###第一条评论](https://juejin.cn/post/6844903681087930375)

**Comment by acepilot3000** [comment]
lettuce-core 至 5.3.0+，可以解决这个问题吗？

**Comment by hdtopku** [comment]
> lettuce-core 至 5.3.0+，可以解决这个问题吗？

不能解决

**Comment by debu99** [comment]
哪里有写官方建议设置 60s 时间？
